version: '3.8'

services:
  belvo_api:
    container_name: belvo_api
    networks:
      - belvo-app
    env_file:
      - "./belvo-app-belvo-api/.env"
    build: 
      context: ./belvo-app-belvo-api
      dockerfile: Dockerfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.belvo_api.rule=Host(`belvo-api.bryancalisaya.lat`)"
      - "traefik.http.routers.belvo_api.entrypoints=websecure"
      - "traefik.http.routers.belvo_api.tls.certresolver=ssl"
      - "traefik.belvo_api.headers.SSLRedirect=true"


  
  belvo_web:
    container_name: belvo_web
    networks:
      - sampling-ai
    command: yarn start
    build: 
      context: ./belvo-app-belvo-web
      dockerfile: Dockerfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.belvo_web.rule=Host(`belvo.bryancalisaya.lat`)"
      - "traefik.http.routers.belvo_web.entrypoints=websecure"
      - "traefik.http.routers.belvo_web.tls.certresolver=ssl"
      - "traefik.belvo_web.headers.SSLRedirect=true"

  
volumes:
  firebase: